name: OpenMRS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types:
      - created

env:
  ESM_NAME: "@pucp-gidis-hiisc/esm-sihsalus-app"
  JS_NAME: "pucp-gidis-hiisc-esm-sihsalus-app.js"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install --immutable
      - run: yarn verify
      - run: yarn build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist

  pre_release:
    runs-on: ubuntu-latest

    needs: build

    if: ${{ github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - run: yarn install --immutable
      - run: git config user.email "info@pucp-gidis-hiisc.org" && git config user.name "PUCP GIDIS HIISC CI"
      - run: yarn config set npmAuthToken "${NODE_AUTH_TOKEN}" && yarn deploy:next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-next
          path: |
            dist

  release:
    runs-on: ubuntu-latest

    needs: build

    if: ${{ github.event_name == 'release' }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --immutable
      - run: git config user.email "info@pucp-gidis-hiisc.org" && git config user.name "PUCP GIDIS HIISC CI"
      - run: yarn config set npmAuthToken "${NODE_AUTH_TOKEN}" && yarn deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  deploy:
    runs-on: ubuntu-latest

    needs: pre_release

    if: ${{ github.event_name == 'push' }}

    steps:
      - run: echo "Uncomment the lines below and delete this one."
      # - name: Trigger RefApp Build
      #   uses: fjogeleit/http-request-action@v1
      #   with:
      #     url: https://ci.openmrs.org/rest/api/latest/queue/O3-BP
      #     method: "POST"
      #     customHeaders: '{ "Authorization": "Bearer ${{ secrets.BAMBOO_TOKEN }}" }'
